### ISSUE TITLE
Task 1: C programming - Implement a Data Structure

### ISSUE THREAD

**Issue by lahiruroot** [lahiruroot/Hacktoberfest2023#1]
### Challenge

- Contribute to an open-source project that involves implementing a data structure in C. It could be a linked list, stack, queue, or any other data structure. Ensure that your code is well-documented and follows best practices for C programming.

**Comment by shishirkj** [comment]
plz assign this to me i would like to work on it

**Comment by Ruberald** [comment]
Do you mind assigning this to me? I would like to add a stack made using linked list.
