### ISSUE TITLE
Task 2: JavaScript - Create a Web Component

### ISSUE THREAD

**Issue by lahiruroot** [lahiruroot/Hacktoberfest2023#2]
###  Challenge

- Collaborate on an open-source web project to create a reusable web component using JavaScript. This component could be a date picker, modal dialog, or any UI element. Ensure that your code is compatible with modern browsers and follows coding standards.

**Comment by shishirkj** [comment]
plz assign this to me i would like to work on it

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.

**Comment by rituraj12797** [comment]
i would like to work on this isuue kindly assign it to me @lahiruroot
