### ISSUE TITLE
Task 3: CSS - Improve Website Styling

### ISSUE THREAD

**Issue by lahiruroot** [lahiruroot/Hacktoberfest2023#3]
### Challenge

- Enhance the styling of an open-source website or web application using CSS. Focus on improving the user interface, layout, and responsiveness. Ensure that your CSS code is clean, organized, and follows best practices.

**Comment by shishirkj** [comment]
plz assign this to me i would like to work on it

**Comment by lahiruroot** [comment]
> plz assign this to me i would like to work on it

Ok I will assign you.

**Comment by saku1331** [comment]
I wish to work on this issue. Kindly assign me this.
